### ISSUE TITLE
Setting a Player's Tokens Gives Console Error

### ISSUE THREAD

**Issue by TheMadog24** [TheCoolestPaul/Tokens#59]
Whenever I set a player's Tokens through the console, it works, but I get an error. trying to set a player's tokens using the in-game chat commands does nothing and gives no error.

**Plugin version:** Latest

**MC Version:** Spigot 1.16.2

**Error message**
```
>tokens set Madog24 0
[16:13:06] [Server thread/INFO]: You set 0 Tokens to Madog24
[16:13:06] [Server thread/WARN]: Unexpected exception while parsing console command "tokens set Madog24 0"
org.bukkit.command.CommandException: Unhandled exception executing command 'tokens' in plugin Tokens v3.9.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:741) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:384) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:353) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
        at net.thirdshift.tokens.messages.MessageHandler.useMessage(MessageHandler.java:25) ~[?:?]
        at net.thirdshift.tokens.commands.tokens.CommandTokens.onCommand(CommandTokens.java:161) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-0d8350a]
        ... 9 more
[16:13:31] [Server thread/INFO]: [Tokens] No newer version available.
```

**Comment by TheCoolestPaul** [comment]
I've actually found the source of this bug. I'm not proud to admit it was a typo on my part. Expect to see it fixed very soon.
