### ISSUE TITLE
ShopGUI+ does not work

### ISSUE THREAD

**Issue by radimnemecek** [TheCoolestPaul/Tokens#71]
**Describe the bug**
>Economy type MYSQL_TOKENS does not work in the latest version (1.61.1+) of the ShopGUI+ plugin
It does not work approximately since version 1.56.0.

**Plugin version:** 4.3.2

**Error message**
>[11:05:06 WARN]: [ShopGUIPlus] Failed to register MYSQL_TOKENS economy.
[11:05:06 WARN]: net.brcdev.shopgui.exception.economy.EconomyProviderLoadException: Error occurred when loading economy provider
[11:05:06 WARN]: 	at net.brcdev.shopgui.economy.EconomyManager.loadEconomyProvider(EconomyManager.java:151)
[11:05:06 WARN]: 	at net.brcdev.shopgui.economy.EconomyManager.registerDefaultProviders(EconomyManager.java:64)
[11:05:06 WARN]: 	at net.brcdev.shopgui.economy.EconomyManager.setup(EconomyManager.java:50)
[11:05:06 WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.loadAfterServerLoaded(ShopGuiPlugin.java:206)
[11:05:06 WARN]: 	at net.brcdev.shopgui.task.LoadShopsTask.run(LoadShopsTask.java:26)
[11:05:06 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81)
[11:05:06 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[11:05:06 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252)
[11:05:06 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436)
[11:05:06 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
[11:05:06 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027)
[11:05:06 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[11:05:06 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[11:05:06 WARN]: [ShopGUIPlus] No supported economy plugins found, disabling the plugin.
[11:05:06 INFO]: [ShopGUIPlus] Disabling ShopGUIPlus v1.61.1

**Comment by TheCoolestPaul** [comment]
This is not MYSQL_TOKENS. This resource's ShopGUIPlus is just "Tokens"

**Comment by radaoggy** [comment]
The plugin page says that it supports ShopGUI+ and worked for me in an older version. Due to 1.17 I had to update ShopGUI+ and it no longer works. So how do I set up ShopGUI+ to still support Tokens?

**Comment by radimnemecek** [comment]
I tried to repair it, but it doesn't find this type of economy at all. _So how do I set ShopGUI+ to use tokens from this plugin?_

I don't understand that MYSQL_TOKENS worked without a problem in the older version of ShopGUI+.

**Comment by radimnemecek** [comment]
[09:07:07 INFO]: Enabling ShopGUIPlus v1.61.1
[09:07:07 INFO]: Enabling Tokens v4.3.2
[09:07:07 INFO]: Loading keys
[09:07:07 INFO]: Added Key{keyString='exampleKey', enabled=false, oneTime=true, tokens=5, cooldown=0}
[09:07:07 INFO]: Added Key{keyString='TestKey123', enabled=true, oneTime=true, tokens=10, cooldown=0}
[09:07:07 INFO]: Added Key{keyString='BestKey1234', enabled=true, oneTime=false, tokens=2, cooldown=60}
[09:07:07 INFO]: Finished adding 3 keys
[09:07:07 INFO]: Starting to load KeyData
[09:07:07 INFO]: Finished loading KeyData
[09:07:07 INFO]: Database Connection: opening a connection to the SQLite database.
[09:07:07 INFO]: Storage Type: [ SQLLite ] | MySQL ( Default )
[09:07:07 INFO]: Registered custom economy provider 'Tokens'.
[09:07:07 INFO]: Successfully registered Tokens as ShopGUI+ economy
[09:07:07 WARN]: You don't have any supported plugins enabled.
[09:07:07 INFO]: TokenCache: tokencache.is_enabled: true    tokencache.write_delay: 10000
[09:07:07 INFO]: Added module add
[09:07:07 INFO]: Added module give
[09:07:07 INFO]: Added module help
[09:07:07 INFO]: Added module key
[09:07:07 INFO]: Added module reload
[09:07:07 INFO]: Added module remove
[09:07:07 INFO]: Added module set
[09:07:07 INFO]: Added module cache
[09:07:07 INFO]: Database Connection: opening a connection to the SQLite database.
[09:07:07 INFO]: Storage Type: [ SQLLite ] | MySQL ( Default )
[09:07:07 INFO]: Registered custom economy provider 'Tokens'.
[09:07:07 INFO]: Successfully registered Tokens as ShopGUI+ economy
[09:07:07 WARN]: You don't have any supported plugins enabled.
[09:07:07 INFO]: Will check for updates every 5 hours.
[09:07:07 INFO]: Running delayed init tasks
[09:07:07 INFO]: Checking for an update
[09:07:08 INFO]: Tokens is up to date.
[09:07:08 INFO]: No newer version available.
[09:07:08 INFO]: ================================[ ShopGUI+ 1.61.1 ]================================
[09:07:08 INFO]:  
**[09:07:08 WARN]: No supported economy plugins found, disabling the plugin.**
[09:07:08 INFO]: Disabling ShopGUIPlus v1.61.1

![image](https://user-images.githubusercontent.com/35913447/123051946-9208b780-d402-11eb-87a3-c434c6e00f17.png)

![image](https://user-images.githubusercontent.com/35913447/123052027-aa78d200-d402-11eb-886e-5ce9d2a36cd5.png)

![image](https://user-images.githubusercontent.com/35913447/123051979-9c2ab600-d402-11eb-8159-264c09d2ad4c.png)

**Comment by TheCoolestPaul** [comment]
I'll start looking into it, MYSQL_TOKENS is a similar but different plugin. There is a good chance that in the last few versions of ShopGUI+ they changed how some things work. I apologize for immediately invalidating this issue.

**Comment by radimnemecek** [comment]
Will you continue to develop this plugin? It's perfect and I love its features.

**Comment by TheCoolestPaul** [comment]
After looking at the ShopGUI+ github, it seems that they've changed their API after version 1.57.0 I'll have to re-code my connection to ShopGUI+ expect to see it in the next update.

**Comment by TheCoolestPaul** [comment]
> 
> 
> Will you continue to develop this plugin? It's perfect and I love its features.

I've already fixed support for ShopGUI+ in the coming pull request. I'll link it in a bit.

**Comment by TheCoolestPaul** [comment]
[Have fun with this](https://github.com/TheCoolestPaul/Tokens/wiki/ShopGUI--Support)
